name: 'Standard python Linting and formatting toolkit'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  run-linting-formatting:
    runs-on: ubuntu-24.04 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' 
    - run: pip install -r requirements.txt
    - run: ruff check --verbose
    - run: black --diff reddit-analysis.py
    - run: bandit -r reddit-analysis.py --verbose
    - run: mypy reddit-analysis.py

  run-ruff:
    runs-on: ubuntu-24.04 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' 
    - run: pip install -r requirements.txt
    - run: ruff check --verbose

  run-black:
    runs-on: ubuntu-24.04 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' 
    - run: pip install -r requirements.txt
    - run: black --diff reddit-analysis.py